# -*- coding: utf-8 -*-
"""Python - Internal Assessment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bo4pPgpbT2haqFUib1VIoYOl6dMSwtIr

PYTHON - INTERNAL ASSESSMENT 1

LAB 1
"""

## Qn-1

print("Enter the details to find the area of the commercial properties")
length = int(input("Enter the Length in metres: "))
width = int(input("Enter the Width in metres: "))

area = length * width

print("The Total Area of the property in Sq.Metres : ", area, "Sq.Metres")

if(area<=1000):
  print("The property size is Small.")

elif(area>1000 and area<=2500):
  print("The property size is Medium.")

elif(area<2500):
  print("The property size is Large.")

## Qn-2

height = int(input("Enter your Height in cm: "))
weight = int(input("Enter your Weight in kg: "))

bmi = float((height/weight) * 12)

print("Your BMI score : ", bmi)

if(bmi<20):
  print("You are underweight and need to Gain Mass. Take healthy foods. Stay Strong")

elif(bmi>=20 and bmi<=25):
  print("You are normal and Be fit like the same. Stay Strong")

elif(bmi>25):
  print("You are Overweight and need to lose your weight. Do exercise and be fit")

## Qn-3

studentGrades = {"Hrithik":["A","O","A+","A"],
                 "Keerthik":["O","A","B+","A"],
                 "Roshan":["B","B+","A","A"]}

print(studentGrades)

## Qn-4

print("Welcome!!")
age = int(input("Enter your Age: "))

if(age>0):
  if(age<12):
    print("You fall under Children category. We recommend you to watch U Films and Cartoon, Animation Films")

  elif(age>=12 and age<18):
    print("You fall under Teen category. We recommend you to watch U, U/A Films and Films under Teen category")

  elif(age>=18 and age<=50):
    print("We recommend you to watch all films under every category")

  else:
      print("We recommend you to watch all films under seniors category like comicals, mythology, philosophy etc,.")

else:
  print("Enter the correct age")

## Qn-5

list_l = []
even_IDs = []

total_count = int(input("Enter the Total Number of Subscribers from the database: "))

print("Enter their Subscriber IDs: ")

for i in range(0,total_count):
  list_l.append(int(input()))

for ids in list_l:
  if (int(ids%2)) == 0:
    even_IDs.append(ids)

print("The List with even-numbered Subscriber IDs are : ", even_IDs)

## Qn-6

existing_password = "abcdef"

def check():
  password = input("Enter the Password: ")

  if(password!=existing_password):
    print("Retry!!")
    check()

  else:
    print("Correct Password")

check()

## Qn-7

n = int(input("Enter the number of scores: "))
sum = 0

print("Enter the scores ranges between 0 and 10")

for i in range(0,n):
  i = int(input())
  sum += i

average = float(sum/n)

if(average<=5):
  print("Feedback are quite bad and Services needs to improve more")

elif(average>5 and average<8):
  print("Feedback are quite normal but Services needs to improve")

elif(average>=8):
  print("Feedback are good with customer satisfaction")

## Qn-8

string_s = input("Enter the sentence: ")
count = 0

for i in string_s:
  if i=='a' or i=='e'or i=='i' or i=='o' or i=='u' or i=='A' or i=='E'or i=='I' or i=='O' or i=='U':
    count += 1

print("Number of vowels in the sentence: ",count)

## Qn-9

import datetime

ct = datetime.datetime.now()
print(ct)

## Qn-10

def customerDetails():

  loan = float(input())
  interest_rate = float(input())

  print("Total AMount: ", loan*interest_rate)

  customer_details()

## Qn-11

## Qn-12

def division(number, divisor):
  number = int(input("Enter the number to be divided: "))
  divisor = int(input("Enter the divisor: "))

  try:
    quotient = number/divisor
    print("Quotient: ",quotient)

  except ZeroDivisionError:
      print("Enter the divisor other than 0")
      division(number, divisor)

division(number, divisor)

## Qn-13

file_f = open("/content/reports.txt", "w")

file_f.write(input("Enter the Daily Status: "))
file_f.close()

file_f = open("/content/reports.txt", "r")
print(file_f.read())
file_f.close()

## Qn-14

file_f = open("/content/reports.txt", "r")

print(file_f.read())
file_f.close()

## Qn-15

file_f = open("/content/reports.txt", "a")

file_f.write(input("Enter the Daily Status to be append: "))
file_f.close()

file_f = open("/content/reports.txt", "r")
print(file_f.read())
file_f.close()